# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
    - pre-commit
    - post-checkout
    - post-merge
    - post-rewrite
repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.7.17
      hooks:
          # Update the uv lockfile
          - id: uv-lock
          - id: uv-export
            # Don't echo the entire lockfile to stdout, thank you very much.
            args: [--quiet]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.1
      hooks:
          # Run the linter.
          - id: ruff-check
            # Run the linter with fix.
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: detect-private-key
